-- Reference SQL schema (auto-generated by SQLAlchemy at runtime).
-- Kept here as a human-readable reference for the database structure.

CREATE TABLE IF NOT EXISTS users (
    id              INTEGER PRIMARY KEY,
    telegram_id     INTEGER UNIQUE NOT NULL,
    username        TEXT,
    dry_run         BOOLEAN DEFAULT 1,
    stop_loss_pct   REAL DEFAULT 15.0,
    max_buy_ton     REAL DEFAULT 10.0,
    min_profit_ton  REAL DEFAULT 0.05,
    large_deal_ton  REAL DEFAULT 5.0,
    max_daily_loss_ton REAL DEFAULT 20.0,
    max_daily_trades INTEGER DEFAULT 50,
    proxy_url       TEXT,
    notifications   TEXT DEFAULT '{}',
    auto_trading    BOOLEAN DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_filters (
    id                  INTEGER PRIMARY KEY,
    user_id             INTEGER REFERENCES users(id),
    collection_names    TEXT DEFAULT '[]',
    model_names         TEXT DEFAULT '[]',
    backdrop_names      TEXT DEFAULT '[]',
    symbol_names        TEXT DEFAULT '[]',
    min_price           REAL,
    max_price           REAL,
    ordering            TEXT DEFAULT 'Price',
    low_to_high         BOOLEAN DEFAULT 1,
    mintable_only       BOOLEAN DEFAULT 0,
    number_filter       INTEGER,
    rarity_min          REAL,
    is_active           BOOLEAN DEFAULT 1,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS strategies (
    id              INTEGER PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id),
    name            TEXT NOT NULL,
    type            TEXT NOT NULL,
    params          TEXT NOT NULL,
    is_active       BOOLEAN DEFAULT 0,
    filter_id       INTEGER REFERENCES user_filters(id),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id              INTEGER PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id),
    strategy_id     INTEGER REFERENCES strategies(id),
    order_type      TEXT NOT NULL,
    gift_id         TEXT,
    gift_name       TEXT,
    collection      TEXT,
    model           TEXT,
    backdrop        TEXT,
    symbol          TEXT,
    model_rarity    REAL,
    backdrop_rarity REAL,
    symbol_rarity   REAL,
    rarity_score    REAL,
    number          INTEGER,
    price           REAL NOT NULL,
    target_price    REAL,
    status          TEXT DEFAULT 'active',
    dry_run         BOOLEAN DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    filled_at       TIMESTAMP,
    cancelled_at    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio (
    id              INTEGER PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id),
    gift_id         TEXT UNIQUE NOT NULL,
    gift_name       TEXT,
    collection      TEXT,
    model           TEXT,
    backdrop        TEXT,
    symbol          TEXT,
    rarity_score    REAL,
    number          INTEGER,
    buy_price       REAL NOT NULL,
    buy_order_id    INTEGER REFERENCES orders(id),
    target_sell     REAL,
    stop_loss_price REAL,
    cooldown_until  TIMESTAMP,
    bought_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    listed_at       TIMESTAMP,
    strategy_id     INTEGER REFERENCES strategies(id)
);

CREATE TABLE IF NOT EXISTS trades (
    id              INTEGER PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id),
    gift_id         TEXT,
    gift_name       TEXT,
    collection      TEXT,
    rarity_score    REAL,
    buy_price       REAL,
    sell_price      REAL,
    commission      REAL,
    gross_profit    REAL,
    net_profit      REAL,
    profit_pct      REAL,
    hold_time_sec   INTEGER,
    strategy_id     INTEGER,
    dry_run         BOOLEAN,
    is_stop_loss    BOOLEAN DEFAULT 0,
    bought_at       TIMESTAMP,
    sold_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS price_history (
    id              INTEGER PRIMARY KEY,
    collection      TEXT NOT NULL,
    model           TEXT,
    floor_price     REAL,
    min_price       REAL,
    max_price       REAL,
    avg_price       REAL,
    volume_count    INTEGER,
    recorded_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_log (
    id              INTEGER PRIMARY KEY,
    level           TEXT,
    module          TEXT,
    message         TEXT,
    data            TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_user_status ON orders(user_id, status);
CREATE INDEX IF NOT EXISTS idx_portfolio_user ON portfolio(user_id);
CREATE INDEX IF NOT EXISTS idx_trades_user_date ON trades(user_id, sold_at);
CREATE INDEX IF NOT EXISTS idx_price_history_collection ON price_history(collection, recorded_at);
