"""Auto-generated from gifts.supply public catalog API.

DO NOT EDIT BY HAND. Run scripts/refresh_collections.py to regenerate.
"""
from __future__ import annotations

BACKDROPS: list[str] = ['Amber', 'Aquamarine', 'Azure Blue', 'Battleship Grey', 'Black', 'Burgundy', 'Camo Green', 'Cappuccino', 'Carmine', 'Carrot Juice', 'Celtic Blue', 'Cobalt Blue', 'Coral Red', 'Cyberpunk', 'Dark Lilac', 'Deep Cyan', 'Desert Sand', 'Electric Indigo', 'Electric Purple', 'Emerald', 'English Violet', 'Fandango', 'Feldgrau', 'Fire Engine', 'French Blue', 'Grape', 'Gunmetal', 'Gunship Green', 'Hunter Green', 'Indigo Dye', 'Ivory White', 'Khaki Green', 'Lavender', 'Lemongrass', 'Light Olive', 'Marine Blue', 'Mint Green', 'Moonstone', 'Mustard', 'Mystic Pearl', 'Navy Blue', 'Neon Blue', 'Old Gold', 'Onyx Black', 'Orange', 'Pacific Cyan', 'Pacific Green', 'Persimmon', 'Pistachio', 'Platinum', 'Pure Gold', 'Purple', 'Ranger Green', 'Roman Silver', 'Rosewood', 'Sapphire', 'Satin Gold', 'Shamrock Green', 'Silver Blue', 'Sky Blue', 'Steel Grey', 'Turquoise']

SYMBOLS: list[str] = ['Alarm', 'Autumn Leaves', 'Baby Bottle', 'Banner', 'Bishop', 'Black Cat', 'Bottle', 'Bow Tie', 'Bunny Ears', 'Burger', 'Cactus', 'Candle', 'Candy', 'Cap', 'Cauldron', 'Cicada', 'Clover', 'Cocktail', 'Conch', 'Cookie', 'Croissant', 'Crystal Ball', 'Cupid’s Arrow', 'Dessert', 'Fish', 'Fish Skeleton', 'Geisha Fan', 'Ghost', 'Gingerbread', 'Gravestone', 'Griffon', 'Grim Reaper', 'Hersir', 'Ice Skates', 'Inguz Rune', 'Iron Helmet', 'Key', 'Kudu Totem', 'Lightning', 'Lily', 'Lotus Flower', 'Loveberry', 'Lovely Key', 'Magic Wand', 'Mannaz Rune', 'Maple', 'Mustache', 'Narcissus', 'Neko Mask', 'Night Bats', 'Ornament', 'Paschal Lamb', 'Passion Latte', 'Pereira', 'Pirate Scull', 'Plume', 'Poison Drop', 'Police Hat', 'Pomegranate', 'Potion', 'Pyramid', 'Rudolph', 'Sauron', 'Seahorse', 'Skull', 'Snow Angel', 'Spider Web', 'Star', 'Sun Mountain', 'Sushi Rolls', 'Sword Fight', 'Tamagotchi', 'Tetsubin', 'Tricorne', 'Turban', 'Vinyl Record', 'War Bonnet', 'Winter Hat', 'Winter House']

COLLECTIONS: list[dict] = [
    {
        'slug': 'SnoopDogg',
        'name': 'Snoop Doggs',
        'floor': 4.94,
        'supply': 577000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 250,
        'listed_count': 45106,
        'preview_models': ['Fish Hat', 'Iconic Dude', 'Huggy Bear', 'Peach Mode', 'Chill Homie'],
        'preview_backdrop': 'French Blue',
        'preview_symbol': 'Vinyl Record',
        'theme': '',
    },
    {
        'slug': 'ChillFlame',
        'name': 'Chill Flames',
        'floor': 3.95,
        'supply': 500000,
        'models_count': 52,
        'backdrops_count': 80,
        'symbols_count': 300,
        'listed_count': 42876,
        'preview_models': ['Dungeon', 'Spring Grove', 'Candelabra', 'Bowl of Hygeia', 'Spaceship'],
        'preview_backdrop': 'Old Gold',
        'preview_symbol': 'Police Hat',
        'theme': '',
    },
    {
        'slug': 'ViceCream',
        'name': 'Vice Creams',
        'floor': 3.4,
        'supply': 250000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 300,
        'listed_count': 38961,
        'preview_models': ['Disco Funk', 'Circus', 'Cherry On Top', 'Unicone', 'Birthday'],
        'preview_backdrop': 'Lemongrass',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'IceCream',
        'name': 'Ice Creams',
        'floor': 3.0,
        'supply': 319000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 26017,
        'preview_models': ['Strawberry', 'Choco Almond', 'Crude Oil', 'Kiwi Sorbet', 'Cold Steel'],
        'preview_backdrop': 'Khaki Green',
        'preview_symbol': 'War Bonnet',
        'theme': '',
    },
    {
        'slug': 'LolPop',
        'name': 'Lol Pops',
        'floor': 3.1,
        'supply': 427000,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 256,
        'listed_count': 24386,
        'preview_models': ['Tsunami', 'Prisma', 'Spectrum', 'Iced Latte', 'Bubblegum'],
        'preview_backdrop': 'Pacific Cyan',
        'preview_symbol': 'Pomegranate',
        'theme': 'Food',
    },
    {
        'slug': 'InstantRamen',
        'name': 'Instant Ramens',
        'floor': 2.9,
        'supply': 346000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 250,
        'listed_count': 23593,
        'preview_models': ['First Date', 'Khinkali', 'Mushroom', 'Chicken', 'Sewing Stew'],
        'preview_backdrop': 'Celtic Blue',
        'preview_symbol': 'Sword Fight',
        'theme': '',
    },
    {
        'slug': 'PoolFloat',
        'name': 'Pool Floats',
        'floor': 4.54,
        'supply': 250000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 250,
        'listed_count': 22753,
        'preview_models': ['Sebastian', 'Private Jet', 'Dark Swan', 'Lizard', 'Quacky'],
        'preview_backdrop': 'Moonstone',
        'preview_symbol': 'Geisha Fan',
        'theme': '',
    },
    {
        'slug': 'MoodPack',
        'name': 'Mood Packs',
        'floor': 5.64,
        'supply': 200000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 21011,
        'preview_models': ['Space Cat', 'Angel Wings', 'Burger Bag', 'Bloom Pack', 'Cat Pack'],
        'preview_backdrop': 'Cobalt Blue',
        'preview_symbol': 'Banner',
        'theme': '',
    },
    {
        'slug': 'ToyBear',
        'name': 'Toy Bears',
        'floor': 31.99,
        'supply': 55400,
        'models_count': 70,
        'backdrops_count': 60,
        'symbols_count': 265,
        'listed_count': 19918,
        'preview_models': ['Coral Reef', 'Pineapple', 'Carrot', 'Red Velvet', 'Cherry'],
        'preview_backdrop': 'Platinum',
        'preview_symbol': 'Lovely Key',
        'theme': 'Meme',
    },
    {
        'slug': 'PartySparkler',
        'name': 'Party Sparklers',
        'floor': 4.0,
        'supply': 166000,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 136,
        'listed_count': 19491,
        'preview_models': ['Little Fairy', 'Bubblegum', 'Seafoam', 'Indigo Dance', 'Amethyst'],
        'preview_backdrop': 'Pacific Green',
        'preview_symbol': 'Bow Tie',
        'theme': '',
    },
    {
        'slug': 'SwagBag',
        'name': 'Swag Bags',
        'floor': 5.0,
        'supply': 230000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 175,
        'listed_count': 17328,
        'preview_models': ['Lemon Pepper', 'Smokefest', 'Snoopcoins', 'Dogg’s Loot', 'Lollipops'],
        'preview_backdrop': 'Electric Indigo',
        'preview_symbol': 'Cactus',
        'theme': '',
    },
    {
        'slug': 'EasterEgg',
        'name': 'Easter Eggs',
        'floor': 3.5,
        'supply': 161000,
        'models_count': 62,
        'backdrops_count': 80,
        'symbols_count': 256,
        'listed_count': 17205,
        'preview_models': ['Matryoshka', 'Flowers', 'Porcelain', 'Protein Lamp', 'Purple Bird'],
        'preview_backdrop': 'Sapphire',
        'preview_symbol': 'Seahorse',
        'theme': 'Easter',
    },
    {
        'slug': 'XmasStocking',
        'name': 'Xmas Stockings',
        'floor': 2.89,
        'supply': 186000,
        'models_count': 65,
        'backdrops_count': 80,
        'symbols_count': 203,
        'listed_count': 14723,
        'preview_models': ['Kindergarten', 'Wonderland', 'Bloody', 'Photo Negative', 'Toxic Grape'],
        'preview_backdrop': 'Black',
        'preview_symbol': 'Star',
        'theme': 'Christmas',
    },
    {
        'slug': 'CloverPin',
        'name': 'Clover Pins',
        'floor': 3.939999,
        'supply': 218000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 250,
        'listed_count': 14126,
        'preview_models': ['Top Student', 'Matrix', 'Celtic Knot', 'Glass Rainbow', 'Red Tartan'],
        'preview_backdrop': 'Old Gold',
        'preview_symbol': 'Banner',
        'theme': 'St. Patrick',
    },
    {
        'slug': 'DeskCalendar',
        'name': 'Desk Calendars',
        'floor': 5.68,
        'supply': 336000,
        'models_count': 157,
        'backdrops_count': 60,
        'symbols_count': 256,
        'listed_count': 14088,
        'preview_models': ['Black Suede', 'Orange Mood', 'Tropical', 'Lilac Black', 'Lavendays'],
        'preview_backdrop': 'Pacific Green',
        'preview_symbol': 'Seahorse',
        'theme': 'New Year',
    },
    {
        'slug': 'CandyCane',
        'name': 'Candy Canes',
        'floor': 2.9,
        'supply': 192000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 139,
        'listed_count': 13303,
        'preview_models': ['Starry Cane', 'Minty Mirth', 'Lime Twist', 'Violet Berry', 'Negativus'],
        'preview_backdrop': 'Old Gold',
        'preview_symbol': 'Bow Tie',
        'theme': 'Food',
    },
    {
        'slug': 'LunarSnake',
        'name': 'Lunar Snakes',
        'floor': 2.94,
        'supply': 179000,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 138,
        'listed_count': 13078,
        'preview_models': ['Lancehead', 'Blue Boa', 'Dark Rattle', 'Copperhead', 'Purple Mamba'],
        'preview_backdrop': 'Orange',
        'preview_symbol': 'Snow Angel',
        'theme': '',
    },
    {
        'slug': 'SpicedWine',
        'name': 'Spiced Wines',
        'floor': 3.5,
        'supply': 96300,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 256,
        'listed_count': 12785,
        'preview_models': ['Persimmon', 'Blackout', 'Golden Glow', 'Cranberry Lime', 'Aqua Vita'],
        'preview_backdrop': 'Navy Blue',
        'preview_symbol': 'Seahorse',
        'theme': 'Christmas',
    },
    {
        'slug': 'SkyStilettos',
        'name': 'Sky Stilettos',
        'floor': 12.899999,
        'supply': 48700,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 12407,
        'preview_models': ['Queen Bee', 'Eooxy', 'Diaethria', 'Leopard', 'Machaon'],
        'preview_backdrop': 'Rosewood',
        'preview_symbol': 'Bottle',
        'theme': '',
    },
    {
        'slug': 'WhipCupcake',
        'name': 'Whip Cupcakes',
        'floor': 2.9,
        'supply': 241000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 175,
        'listed_count': 12350,
        'preview_models': ['Zero Sugar', 'Cloud Nine', 'Fantastic Four', 'Heaven Seven', 'Cherry Top'],
        'preview_backdrop': 'Coral Red',
        'preview_symbol': 'Gingerbread',
        'theme': '',
    },
    {
        'slug': 'SnoopCigar',
        'name': 'Snoop Cigars',
        'floor': 13.0,
        'supply': 117000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 176,
        'listed_count': 12221,
        'preview_models': ['Herbalist', 'Ruby Doobie', 'Jade Fade', 'Bandana', 'Old School'],
        'preview_backdrop': 'Satin Gold',
        'preview_symbol': 'Vinyl Record',
        'theme': '',
    },
    {
        'slug': 'HappyBrownie',
        'name': 'Happy Brownies',
        'floor': 4.0,
        'supply': 202000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 250,
        'listed_count': 12094,
        'preview_models': ['Ice Cream', 'Alien', 'Cactus', 'Cherry Cake', 'Slime'],
        'preview_backdrop': 'Black',
        'preview_symbol': 'Alarm',
        'theme': 'Food',
    },
    {
        'slug': 'VictoryMedal',
        'name': 'Victory Medals',
        'floor': 3.7,
        'supply': 150000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 11910,
        'preview_models': ['Great Athlete', 'Dealmaker', 'Crystal Trophy', 'Radiant Order', 'Nice Try'],
        'preview_backdrop': 'Azure Blue',
        'preview_symbol': 'Kudu Totem',
        'theme': 'Gaming',
    },
    {
        'slug': 'LightSword',
        'name': 'Light Swords',
        'floor': 5.2,
        'supply': 123000,
        'models_count': 52,
        'backdrops_count': 80,
        'symbols_count': 257,
        'listed_count': 11449,
        'preview_models': ['Andromeda', 'Double Time', 'Police Droid', 'Low Battery', 'Lotus Saber'],
        'preview_backdrop': 'Camo Green',
        'preview_symbol': 'Candy',
        'theme': '',
    },
    {
        'slug': 'FreshSocks',
        'name': 'Fresh Socks',
        'floor': 3.12,
        'supply': 151000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 250,
        'listed_count': 11314,
        'preview_models': ['Garfield', 'Drumsticks', 'Courage', 'Leopard', 'Passion'],
        'preview_backdrop': 'Mustard',
        'preview_symbol': 'Cap',
        'theme': 'Fashion',
    },
    {
        'slug': 'TimelessBook',
        'name': 'Timeless Books',
        'floor': 6.45,
        'supply': 100000,
        'models_count': 52,
        'backdrops_count': 80,
        'symbols_count': 221,
        'listed_count': 11081,
        'preview_models': ['Academic', 'Herbarium', 'Animal Friends', 'Geometry', 'Paleontology'],
        'preview_backdrop': 'Sky Blue',
        'preview_symbol': 'Fish',
        'theme': '',
    },
    {
        'slug': 'StellarRocket',
        'name': 'Stellar Rockets',
        'floor': 3.4,
        'supply': 132000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 251,
        'listed_count': 10765,
        'preview_models': ['Astro Peach', 'Vintage Toy', 'Lollipop', 'Popsicle', 'Green Jelly'],
        'preview_backdrop': 'Feldgrau',
        'preview_symbol': 'Sushi Rolls',
        'theme': '',
    },
    {
        'slug': 'SpringBasket',
        'name': 'Spring Baskets',
        'floor': 4.949999,
        'supply': 156000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 10758,
        'preview_models': ['Knitty Kitty', 'Chihuahua', 'Trash Bandit', 'Lovely Lamb', 'Capybara'],
        'preview_backdrop': 'Pistachio',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'JesterHat',
        'name': 'Jester Hats',
        'floor': 3.63,
        'supply': 127000,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 256,
        'listed_count': 10645,
        'preview_models': ['Pierrot', 'Rigoletto', 'Party Drink', 'Trick Tones', 'Hot Midday'],
        'preview_backdrop': 'Azure Blue',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'FaithAmulet',
        'name': 'Faith Amulets',
        'floor': 4.3,
        'supply': 127000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 161,
        'listed_count': 10634,
        'preview_models': ['Mystic Tide', 'Rose Gold', 'Rose Pearl', 'Crystal Leaf', 'Constellation'],
        'preview_backdrop': 'Mystic Pearl',
        'preview_symbol': 'Conch',
        'theme': 'Mystical',
    },
    {
        'slug': 'JollyChimp',
        'name': 'Jolly Chimps',
        'floor': 6.04,
        'supply': 113000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 250,
        'listed_count': 9918,
        'preview_models': ['Baby Kong', 'Patchwork', 'Artist', 'Jungle Pop', 'Clash Elixir'],
        'preview_backdrop': 'Onyx Black',
        'preview_symbol': 'Hersir',
        'theme': '',
    },
    {
        'slug': 'HomemadeCake',
        'name': 'Homemade Cakes',
        'floor': 3.9,
        'supply': 171000,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 256,
        'listed_count': 9546,
        'preview_models': ['Sweet Bite', 'Pink Velvet', 'Pumpkin Pie', 'Lilac Splash', 'Rosy Frost'],
        'preview_backdrop': 'Orange',
        'preview_symbol': 'Seahorse',
        'theme': 'Food',
    },
    {
        'slug': 'InputKey',
        'name': 'Input Keys',
        'floor': 5.05,
        'supply': 122000,
        'models_count': 60,
        'backdrops_count': 80,
        'symbols_count': 251,
        'listed_count': 9197,
        'preview_models': ['Woodland', 'Swimming Pool', 'Coffee', 'Hashtag', 'Parking Lot'],
        'preview_backdrop': 'Platinum',
        'preview_symbol': 'Griffon',
        'theme': '',
    },
    {
        'slug': 'RecordPlayer',
        'name': 'Record Players',
        'floor': 15.0,
        'supply': 31800,
        'models_count': 100,
        'backdrops_count': 80,
        'symbols_count': 257,
        'listed_count': 8961,
        'preview_models': ['Barbie Rock', 'Pink Noir', 'Purple Swag', 'Gentle Soul', 'Maroon'],
        'preview_backdrop': 'Dark Lilac',
        'preview_symbol': 'Winter Hat',
        'theme': '',
    },
    {
        'slug': 'MoonPendant',
        'name': 'Moon Pendants',
        'floor': 4.349999,
        'supply': 101000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 161,
        'listed_count': 8875,
        'preview_models': ['Frozen Light', 'Silver Moon', 'Copper Alloy', 'Stellar Grace', 'Titanium'],
        'preview_backdrop': 'Purple',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'SpyAgaric',
        'name': 'Spy Agarics',
        'floor': 5.24,
        'supply': 86200,
        'models_count': 80,
        'backdrops_count': 60,
        'symbols_count': 136,
        'listed_count': 8868,
        'preview_models': ['Monoshroom', 'Cloudy', 'Mysctic', 'Bleached', 'Herbalist'],
        'preview_backdrop': 'English Violet',
        'preview_symbol': 'Candle',
        'theme': '',
    },
    {
        'slug': 'SnakeBox',
        'name': 'Snake Boxes',
        'floor': 2.8,
        'supply': 155000,
        'models_count': 70,
        'backdrops_count': 80,
        'symbols_count': 137,
        'listed_count': 8626,
        'preview_models': ['Emerald', 'Black Box', 'Holly Jolly', 'Bluebell', 'Sunshine'],
        'preview_backdrop': 'Gunmetal',
        'preview_symbol': 'Burger',
        'theme': '',
    },
    {
        'slug': 'GingerCookie',
        'name': 'Ginger Cookies',
        'floor': 3.9,
        'supply': 135000,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 137,
        'listed_count': 8608,
        'preview_models': ['Candy Bar', 'Pistachio', 'Strawberry', 'Toffee', 'Cheesecake'],
        'preview_backdrop': 'Lemongrass',
        'preview_symbol': 'Cookie',
        'theme': 'Food',
    },
    {
        'slug': 'PetSnake',
        'name': 'Pet Snakes',
        'floor': 3.5,
        'supply': 167078,
        'models_count': 60,
        'backdrops_count': 80,
        'symbols_count': 137,
        'listed_count': 8526,
        'preview_models': ['Rainforest', 'Mojito', 'Lava Viper', 'Sour Bites', 'Lollipop'],
        'preview_backdrop': 'English Violet',
        'preview_symbol': 'Bow Tie',
        'theme': '',
    },
    {
        'slug': 'SakuraFlower',
        'name': 'Sakura Flowers',
        'floor': 11.8,
        'supply': 87400,
        'models_count': 100,
        'backdrops_count': 80,
        'symbols_count': 256,
        'listed_count': 8107,
        'preview_models': ['Cosmea', 'Lunaris', 'Vanilla', 'Sylvaris', 'Violet'],
        'preview_backdrop': 'Neon Blue',
        'preview_symbol': 'Seahorse',
        'theme': 'Nature',
    },
    {
        'slug': 'CookieHeart',
        'name': 'Cookie Hearts',
        'floor': 3.9,
        'supply': 175000,
        'models_count': 99,
        'backdrops_count': 60,
        'symbols_count': 229,
        'listed_count': 7729,
        'preview_models': ['Rosaria', 'Winterfell', 'Mint Cream', 'Midsummer', 'Schnecken'],
        'preview_backdrop': 'Pacific Green',
        'preview_symbol': 'Bow Tie',
        'theme': 'Valentine',
    },
    {
        'slug': 'SantaHat',
        'name': 'Santa Hats',
        'floor': 3.19,
        'supply': 65400,
        'models_count': 69,
        'backdrops_count': 60,
        'symbols_count': 140,
        'listed_count': 7612,
        'preview_models': ['Evergreen', 'Whipped Lime', 'Sunset', 'Lagoon', 'Below Zero'],
        'preview_backdrop': 'Navy Blue',
        'preview_symbol': 'Ice Skates',
        'theme': '',
    },
    {
        'slug': 'MoneyPot',
        'name': 'Money Pots',
        'floor': 3.699999,
        'supply': 120000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 250,
        'listed_count': 7343,
        'preview_models': ['Apiary', 'Dim Sum', 'Witch Brew', 'Snake Charmer', 'Lucky Duck'],
        'preview_backdrop': 'Deep Cyan',
        'preview_symbol': 'Tricorne',
        'theme': '',
    },
    {
        'slug': 'LowRider',
        'name': 'Low Riders',
        'floor': 46.0,
        'supply': 23400,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 175,
        'listed_count': 7337,
        'preview_models': ['Chevy 1964', 'Malibu', 'Silver Angel', 'DeVille 1968', 'Brown Sugar'],
        'preview_backdrop': 'Desert Sand',
        'preview_symbol': 'Tamagotchi',
        'theme': '',
    },
    {
        'slug': 'BigYear',
        'name': 'Big Years',
        'floor': 2.76,
        'supply': 70900,
        'models_count': 55,
        'backdrops_count': 80,
        'symbols_count': 256,
        'listed_count': 7286,
        'preview_models': ['Bitcoin', 'Pokeball', 'Matrix', 'Freddy', 'Emo Music'],
        'preview_backdrop': 'Moonstone',
        'preview_symbol': 'Seahorse',
        'theme': 'New Year',
    },
    {
        'slug': 'MousseCake',
        'name': 'Mousse Cakes',
        'floor': 3.7,
        'supply': 139000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 226,
        'listed_count': 7080,
        'preview_models': ['Glacier', 'Meringue', 'Chocolate', 'Gummy Bears', 'Honey Cake'],
        'preview_backdrop': 'Hunter Green',
        'preview_symbol': 'Mustache',
        'theme': '',
    },
    {
        'slug': 'TamaGadget',
        'name': 'Tama Gadgets',
        'floor': 3.419999,
        'supply': 97400,
        'models_count': 90,
        'backdrops_count': 80,
        'symbols_count': 256,
        'listed_count': 6561,
        'preview_models': ['Amber', 'Lime Shock', 'Bronze', 'Inferno', 'Orchid'],
        'preview_backdrop': 'Silver Blue',
        'preview_symbol': 'Sun Mountain',
        'theme': '',
    },
    {
        'slug': 'WitchHat',
        'name': 'Witch Hats',
        'floor': 4.25,
        'supply': 82000,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 138,
        'listed_count': 6496,
        'preview_models': ['Luminous', 'Ube Tea', 'Junk Mage', 'Sand Cloak', 'Lorendale'],
        'preview_backdrop': 'Aquamarine',
        'preview_symbol': 'Skull',
        'theme': 'Halloween',
    },
    {
        'slug': 'PrettyPosy',
        'name': 'Pretty Posies',
        'floor': 3.73,
        'supply': 200000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 201,
        'listed_count': 6422,
        'preview_models': ['Lavender', 'Rich Lilac', 'Payday', 'Precious', 'Hollywood'],
        'preview_backdrop': 'Pure Gold',
        'preview_symbol': 'Croissant',
        'theme': '',
    },
    {
        'slug': 'RestlessJar',
        'name': 'Restless Jars',
        'floor': 4.3,
        'supply': 96000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 262,
        'listed_count': 6268,
        'preview_models': ['Chocolate', 'Cotton Candy', 'Cold Mint', 'Pineapple', 'Blueberry'],
        'preview_backdrop': 'Pistachio',
        'preview_symbol': 'Loveberry',
        'theme': '',
    },
    {
        'slug': 'WinterWreath',
        'name': 'Winter Wreaths',
        'floor': 3.0,
        'supply': 67200,
        'models_count': 70,
        'backdrops_count': 80,
        'symbols_count': 139,
        'listed_count': 5893,
        'preview_models': ['Spirit', 'Pumpkin', 'Old Movie', 'Comics', 'Starry Night'],
        'preview_backdrop': 'Mint Green',
        'preview_symbol': 'Winter House',
        'theme': '',
    },
    {
        'slug': 'FlyingBroom',
        'name': 'Flying Brooms',
        'floor': 10.499999,
        'supply': 24600,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 138,
        'listed_count': 5749,
        'preview_models': ['Dark Pine', 'Yellowtail', 'Pink Plume', 'Nimbus', 'Stealth Sweep'],
        'preview_backdrop': 'Shamrock Green',
        'preview_symbol': 'Sauron',
        'theme': 'Halloween',
    },
    {
        'slug': 'BowTie',
        'name': 'Bow Ties',
        'floor': 4.239999,
        'supply': 53400,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 256,
        'listed_count': 5664,
        'preview_models': ['Classic', 'Bordeaux', 'Red Rose', 'Cupid’s Bow', 'Cherries'],
        'preview_backdrop': 'Pistachio',
        'preview_symbol': 'Paschal Lamb',
        'theme': 'Fashion',
    },
    {
        'slug': 'EvilEye',
        'name': 'Evil Eyes',
        'floor': 6.3,
        'supply': 71900,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 139,
        'listed_count': 5406,
        'preview_models': ['Succubus', 'Periwinkle', 'Grinch Gaze', 'Grayscale', '8 Ball'],
        'preview_backdrop': 'Dark Lilac',
        'preview_symbol': 'Grim Reaper',
        'theme': 'Mystical',
    },
    {
        'slug': 'HypnoLollipop',
        'name': 'Hypno Lollipops',
        'floor': 3.5,
        'supply': 76000,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 256,
        'listed_count': 5383,
        'preview_models': ['Windmill', 'Scary Movie', 'Going Green', 'Nightfall', 'Green Mist'],
        'preview_backdrop': 'Moonstone',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'StarNotepad',
        'name': 'Star Notepads',
        'floor': 3.75,
        'supply': 65600,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 256,
        'listed_count': 5367,
        'preview_models': ['Skies Above', 'Newmarket', 'Candy Pink', 'Tangerine', 'Cheerleader'],
        'preview_backdrop': 'Khaki Green',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'HolidayDrink',
        'name': 'Holiday Drinks',
        'floor': 3.2,
        'supply': 76800,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 203,
        'listed_count': 4990,
        'preview_models': ['Apple Mousse', 'Mango Blast', 'Rose Velvet', 'Banana Split', 'Black Russian'],
        'preview_backdrop': 'Persimmon',
        'preview_symbol': 'Winter House',
        'theme': '',
    },
    {
        'slug': 'JingleBells',
        'name': 'Jingle Bells',
        'floor': 7.999999999,
        'supply': 79900,
        'models_count': 151,
        'backdrops_count': 60,
        'symbols_count': 139,
        'listed_count': 4853,
        'preview_models': ['Cyber Glow', 'Lithograph', 'Pink Twilight', 'Placeholder', 'Heatwave'],
        'preview_backdrop': 'Black',
        'preview_symbol': 'Cocktail',
        'theme': '',
    },
    {
        'slug': 'DiamondRing',
        'name': 'Diamond Rings',
        'floor': 25.99,
        'supply': 32200,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 296,
        'listed_count': 4821,
        'preview_models': ['Mikado Yellow', 'Copper Rose', 'Blue Pearl', 'Red Light', 'Topaz'],
        'preview_backdrop': 'Lavender',
        'preview_symbol': 'Key',
        'theme': 'Luxury',
    },
    {
        'slug': 'JellyBunny',
        'name': 'Jelly Bunnies',
        'floor': 5.5,
        'supply': 98200,
        'models_count': 99,
        'backdrops_count': 60,
        'symbols_count': 256,
        'listed_count': 4798,
        'preview_models': ['Spooky', 'Smelly', 'Ballistics Gel', 'Chili Pepper', 'Red Hot'],
        'preview_backdrop': 'Light Olive',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'HexPot',
        'name': 'Hex Pots',
        'floor': 3.979999,
        'supply': 54100,
        'models_count': 80,
        'backdrops_count': 60,
        'symbols_count': 138,
        'listed_count': 4642,
        'preview_models': ['Witchy', 'Blue Inferno', 'Potpourri', 'Orchid Volt', 'Citrus'],
        'preview_backdrop': 'Cyberpunk',
        'preview_symbol': 'Candle',
        'theme': '',
    },
    {
        'slug': 'LushBouquet',
        'name': 'Lush Bouquets',
        'floor': 4.449999,
        'supply': 99200,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 263,
        'listed_count': 4490,
        'preview_models': ['Donuts', 'Maple Leaves', 'Silvershade', 'Cotton', 'Missing Shoe'],
        'preview_backdrop': 'Pacific Green',
        'preview_symbol': 'Neko Mask',
        'theme': '',
    },
    {
        'slug': 'SnowGlobe',
        'name': 'Snow Globes',
        'floor': 4.49,
        'supply': 49200,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 137,
        'listed_count': 4087,
        'preview_models': ['Amethyst', 'Garnet Dawn', 'Emerald', 'Midas Manor', 'Caramel'],
        'preview_backdrop': 'Ranger Green',
        'preview_symbol': 'Rudolph',
        'theme': '',
    },
    {
        'slug': 'TopHat',
        'name': 'Top Hats',
        'floor': 10.939999,
        'supply': 34000,
        'models_count': 70,
        'backdrops_count': 80,
        'symbols_count': 262,
        'listed_count': 3989,
        'preview_models': ['Maestro', 'Purple Rain', 'Golden Ratio', 'Cardinal', 'Bloodline'],
        'preview_backdrop': 'Ivory White',
        'preview_symbol': 'Pirate Scull',
        'theme': '',
    },
    {
        'slug': 'BerryBox',
        'name': 'Berry Boxes',
        'floor': 6.659999,
        'supply': 48600,
        'models_count': 70,
        'backdrops_count': 60,
        'symbols_count': 192,
        'listed_count': 3877,
        'preview_models': ['Sweet Star', 'White Cocoa', 'Magenta', 'Iridescent', 'Paparazzi'],
        'preview_backdrop': 'Roman Silver',
        'preview_symbol': 'Plume',
        'theme': 'Food',
    },
    {
        'slug': 'EternalCandle',
        'name': 'Eternal Candles',
        'floor': 5.379999,
        'supply': 44900,
        'models_count': 80,
        'backdrops_count': 60,
        'symbols_count': 136,
        'listed_count': 3818,
        'preview_models': ['Purple Wave', 'Dark Desire', 'Carnation', 'Yellow Gold', 'Spiced Apple'],
        'preview_backdrop': 'English Violet',
        'preview_symbol': 'Cauldron',
        'theme': '',
    },
    {
        'slug': 'HangingStar',
        'name': 'Hanging Stars',
        'floor': 7.249999,
        'supply': 42700,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 139,
        'listed_count': 3594,
        'preview_models': ['Bubble Gum', 'Milkshake', 'Сarambola', 'Limonello', 'Glacier'],
        'preview_backdrop': 'Battleship Grey',
        'preview_symbol': 'Ornament',
        'theme': 'Christmas',
    },
    {
        'slug': 'SnowMittens',
        'name': 'Snow Mittens',
        'floor': 4.5,
        'supply': 36800,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 138,
        'listed_count': 3557,
        'preview_models': ['Mintens', 'Heather', 'Father Frost', 'Pink Cuffs', 'Grape Soda'],
        'preview_backdrop': 'Carrot Juice',
        'preview_symbol': 'Dessert',
        'theme': '',
    },
    {
        'slug': 'SwissWatch',
        'name': 'Swiss Watches',
        'floor': 42.999,
        'supply': 25300,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 198,
        'listed_count': 3461,
        'preview_models': ['Blue Bezel', 'The Original', 'Gold Band', 'Royal Purple', 'Patrician'],
        'preview_backdrop': 'Mystic Pearl',
        'preview_symbol': 'Mannaz Rune',
        'theme': 'Luxury',
    },
    {
        'slug': 'LovePotion',
        'name': 'Love Potions',
        'floor': 12.599999,
        'supply': 28900,
        'models_count': 70,
        'backdrops_count': 60,
        'symbols_count': 264,
        'listed_count': 3451,
        'preview_models': ['Copper Sulfate', 'Royal Spritz', 'Starry Night', 'Juliet', 'Berry Bomb'],
        'preview_backdrop': 'Persimmon',
        'preview_symbol': 'Loveberry',
        'theme': '',
    },
    {
        'slug': 'CrystalBall',
        'name': 'Crystal Balls',
        'floor': 9.799999,
        'supply': 26600,
        'models_count': 55,
        'backdrops_count': 60,
        'symbols_count': 138,
        'listed_count': 3333,
        'preview_models': ['Prophet', 'Death Wish', 'Ghosted', 'Peridot', 'Silver'],
        'preview_backdrop': 'Platinum',
        'preview_symbol': 'Fish Skeleton',
        'theme': 'Mystical',
    },
    {
        'slug': 'CupidCharm',
        'name': 'Cupid Charms',
        'floor': 16.5,
        'supply': 29400,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 3286,
        'preview_models': ['Golden Grasp', 'White Claws', 'Pink Zebra', 'Glamour', 'Gemstones'],
        'preview_backdrop': 'Ranger Green',
        'preview_symbol': 'Loveberry',
        'theme': 'Valentine',
    },
    {
        'slug': 'JoyfulBundle',
        'name': 'Joyful Bundles',
        'floor': 5.7,
        'supply': 72900,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 3111,
        'preview_models': ['Safari', 'Strawberry', 'Patchwork', 'Watermelon', 'Lovesick'],
        'preview_backdrop': 'Ranger Green',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'BunnyMuffin',
        'name': 'Bunny Muffins',
        'floor': 6.99,
        'supply': 48900,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 189,
        'listed_count': 3063,
        'preview_models': ['Classic', 'Latte', 'Cappuccino', 'Cotton Candy', 'Softness'],
        'preview_backdrop': 'Shamrock Green',
        'preview_symbol': 'Narcissus',
        'theme': 'Easter',
    },
    {
        'slug': 'WestsideSign',
        'name': 'Westside Signs',
        'floor': 85.0,
        'supply': 11400,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 175,
        'listed_count': 2945,
        'preview_models': ['Undead', 'Emerald', 'Duality', 'Paisley', 'Gold Ruby'],
        'preview_backdrop': 'Fire Engine',
        'preview_symbol': 'Clover',
        'theme': '',
    },
    {
        'slug': 'VintageCigar',
        'name': 'Vintage Cigars',
        'floor': 31.99,
        'supply': 25900,
        'models_count': 55,
        'backdrops_count': 60,
        'symbols_count': 199,
        'listed_count': 2820,
        'preview_models': ['Premium Blend', 'Red Devil', 'Aquaviolet', 'Vaporwave', 'Rose Wrapper'],
        'preview_backdrop': 'Electric Purple',
        'preview_symbol': 'Cicada',
        'theme': 'Luxury',
    },
    {
        'slug': 'VoodooDoll',
        'name': 'Voodoo Dolls',
        'floor': 31.818999999,
        'supply': 26700,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 138,
        'listed_count': 2781,
        'preview_models': ['Rebel Spirit', 'Horror Movie', 'Malachite', 'Textile', 'Vengeance'],
        'preview_backdrop': 'Turquoise',
        'preview_symbol': 'Poison Drop',
        'theme': '',
    },
    {
        'slug': 'BDayCandle',
        'name': 'B-Day Candles',
        'floor': 3.6,
        'supply': 256000,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 256,
        'listed_count': 2675,
        'preview_models': ['Twilight Beam', 'Ice Crackle', 'Confetti', 'Cheers', 'Winter Noon'],
        'preview_backdrop': 'Cappuccino',
        'preview_symbol': 'Seahorse',
        'theme': 'Birthday',
    },
    {
        'slug': 'EternalRose',
        'name': 'Eternal Roses',
        'floor': 24.5,
        'supply': 29600,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 191,
        'listed_count': 2457,
        'preview_models': ['Midnight Glow', 'Mystic Frost', 'Lilac Relic', 'Solar Flare', 'Celestial Bud'],
        'preview_backdrop': 'Onyx Black',
        'preview_symbol': 'Key',
        'theme': 'Nature',
    },
    {
        'slug': 'ValentineBox',
        'name': 'Valentine Boxes',
        'floor': 8.9,
        'supply': 33200,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 175,
        'listed_count': 2457,
        'preview_models': ['Green Apple', 'Redshift', 'Snow White', 'Pop Art', 'White Gold'],
        'preview_backdrop': 'Fandango',
        'preview_symbol': 'Lily',
        'theme': '',
    },
    {
        'slug': 'MadPumpkin',
        'name': 'Mad Pumpkins',
        'floor': 11.0,
        'supply': 19200,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 139,
        'listed_count': 2266,
        'preview_models': ['Shamrock', 'Let It Snow', 'Hollow Gold', 'Green Grins', 'Copperfield'],
        'preview_backdrop': 'Sky Blue',
        'preview_symbol': 'Magic Wand',
        'theme': '',
    },
    {
        'slug': 'TrappedHeart',
        'name': 'Trapped Hearts',
        'floor': 11.999999,
        'supply': 24600,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 229,
        'listed_count': 2208,
        'preview_models': ['Abyss Heart', 'Blue Whisper', 'Heartworm', 'Patched Up', 'Phantom'],
        'preview_backdrop': 'Cobalt Blue',
        'preview_symbol': 'Gravestone',
        'theme': '',
    },
    {
        'slug': 'RareBird',
        'name': 'Rare Birds',
        'floor': 23.5,
        'supply': 15000,
        'models_count': 51,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 2164,
        'preview_models': ['Paradise', 'Noble Puffin', 'Pelican', 'Azure Spark', 'Amber Toucan'],
        'preview_backdrop': 'Marine Blue',
        'preview_symbol': 'Seahorse',
        'theme': 'Nature',
    },
    {
        'slug': 'NekoHelmet',
        'name': 'Neko Helmets',
        'floor': 31.0,
        'supply': 15300,
        'models_count': 60,
        'backdrops_count': 80,
        'symbols_count': 263,
        'listed_count': 2086,
        'preview_models': ['Lime Juice', 'Shockwave', 'Silver Surfer', 'Panther', 'Acid Punch'],
        'preview_backdrop': 'Pacific Green',
        'preview_symbol': 'Iron Helmet',
        'theme': '',
    },
    {
        'slug': 'SkullFlower',
        'name': 'Skull Flowers',
        'floor': 10.709999,
        'supply': 21500,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 230,
        'listed_count': 2075,
        'preview_models': ['Dewdrop', 'Sunburst', 'Pink Caprice', 'Daisy', 'Carnation'],
        'preview_backdrop': 'Lavender',
        'preview_symbol': 'Autumn Leaves',
        'theme': '',
    },
    {
        'slug': 'SleighBell',
        'name': 'Sleigh Bells',
        'floor': 6.8,
        'supply': 21000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 256,
        'listed_count': 1951,
        'preview_models': ['Fairycore', 'Green Light', 'Purple Gold', 'Bronze', 'Truffle'],
        'preview_backdrop': 'Neon Blue',
        'preview_symbol': 'Pyramid',
        'theme': '',
    },
    {
        'slug': 'BlingBinky',
        'name': 'Bling Binkies',
        'floor': 24.5,
        'supply': 10000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 1929,
        'preview_models': ['Bloodsucker', 'Ice Pop', 'Shellfish', 'Regent', 'Irish Kiss'],
        'preview_backdrop': 'Cobalt Blue',
        'preview_symbol': 'Turban',
        'theme': '',
    },
    {
        'slug': 'ScaredCat',
        'name': 'Scared Cats',
        'floor': 150.0,
        'supply': 19000,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 138,
        'listed_count': 1915,
        'preview_models': ['Virus', 'Voodoo', 'Puss in Boots', 'Vapurr', 'Cat Nukem'],
        'preview_backdrop': 'Neon Blue',
        'preview_symbol': 'Crystal Ball',
        'theme': 'Meme',
    },
    {
        'slug': 'IonicDryer',
        'name': 'Ionic Dryers',
        'floor': 13.8,
        'supply': 19000,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 241,
        'listed_count': 1853,
        'preview_models': ['Love Burst', 'Air Purrifier', 'Barbiecore', 'Turbo Heat', 'Music Player'],
        'preview_backdrop': 'Gunship Green',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'SignetRing',
        'name': 'Signet Rings',
        'floor': 31.0,
        'supply': 16500,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 198,
        'listed_count': 1836,
        'preview_models': ['Gold', 'White Gold', 'Rose Gold', 'Platinum', 'Golden Pearl'],
        'preview_backdrop': 'Mystic Pearl',
        'preview_symbol': 'Cap',
        'theme': '',
    },
    {
        'slug': 'JackintheBox',
        'name': 'Jacks-in-the-Box',
        'floor': 3.77,
        'supply': 90400,
        'models_count': 58,
        'backdrops_count': 80,
        'symbols_count': 256,
        'listed_count': 1792,
        'preview_models': ['Music Box', 'Knockdown', 'Super Block', 'Bouquet', 'Doughnut'],
        'preview_backdrop': 'Carmine',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'KissedFrog',
        'name': 'Kissed Frogs',
        'floor': 54.0,
        'supply': 14000,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 229,
        'listed_count': 1740,
        'preview_models': ['Lemon Juice', 'Lily Pond', 'Toadberry', 'Sea Breeze', 'Frogwave'],
        'preview_backdrop': 'Persimmon',
        'preview_symbol': 'Skull',
        'theme': '',
    },
    {
        'slug': 'LoveCandle',
        'name': 'Love Candles',
        'floor': 8.7,
        'supply': 22400,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 189,
        'listed_count': 1645,
        'preview_models': ['Ocean Breeze', 'Silver Temple', 'Setting Sun', 'Dreamscape', 'Gentle Wind'],
        'preview_backdrop': 'French Blue',
        'preview_symbol': 'Passion Latte',
        'theme': '',
    },
    {
        'slug': 'LootBag',
        'name': 'Loot Bags',
        'floor': 134.3,
        'supply': 14400,
        'models_count': 80,
        'backdrops_count': 60,
        'symbols_count': 262,
        'listed_count': 1611,
        'preview_models': ['Jaune Citrone', 'Argylle', 'Matte Mint', 'Cherry Red', 'Ombre'],
        'preview_backdrop': 'Burgundy',
        'preview_symbol': 'Lightning',
        'theme': 'Gaming',
    },
    {
        'slug': 'UFCStrike',
        'name': 'UFC Strikes',
        'floor': 12.1,
        'supply': 60000,
        'models_count': 45,
        'backdrops_count': 80,
        'symbols_count': 150,
        'listed_count': 1423,
        'preview_models': ['A. Pereira', 'Classic Blue', 'S. O’Malley', 'I. Adesanya', 'A. Volkanovski'],
        'preview_backdrop': 'Platinum',
        'preview_symbol': 'Pereira',
        'theme': '',
    },
    {
        'slug': 'BondedRing',
        'name': 'Bonded Rings',
        'floor': 42.0,
        'supply': 7800,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 262,
        'listed_count': 1243,
        'preview_models': ['Spectrum', 'Bloody Mary', 'Line Art', 'Frostband', 'Miami Art'],
        'preview_backdrop': 'Cobalt Blue',
        'preview_symbol': 'Baby Bottle',
        'theme': 'Valentine',
    },
    {
        'slug': 'GenieLamp',
        'name': 'Genie Lamps',
        'floor': 43.0,
        'supply': 6400,
        'models_count': 49,
        'backdrops_count': 60,
        'symbols_count': 198,
        'listed_count': 1085,
        'preview_models': ['Gold Tarnish', 'Golden Flame', 'Sahara', 'Chrome', 'Eternal Smoke'],
        'preview_backdrop': 'Rosewood',
        'preview_symbol': 'Sauron',
        'theme': 'Mystical',
    },
    {
        'slug': 'ElectricSkull',
        'name': 'Electric Skulls',
        'floor': 25.0,
        'supply': 9200,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 170,
        'listed_count': 1073,
        'preview_models': ['Bone White', 'Deadman', 'Zombie', 'Ruby Eyes', 'Solar Stone'],
        'preview_backdrop': 'Pacific Green',
        'preview_symbol': 'Night Bats',
        'theme': 'Halloween',
    },
    {
        'slug': 'GemSignet',
        'name': 'Gem Signets',
        'floor': 60.0,
        'supply': 6000,
        'models_count': 49,
        'backdrops_count': 80,
        'symbols_count': 262,
        'listed_count': 1023,
        'preview_models': ['Helios', 'Moonstone', 'Fleur de Mer', 'Amethyst', 'Malibu Pink'],
        'preview_backdrop': 'Fire Engine',
        'preview_symbol': 'Bishop',
        'theme': 'Luxury',
    },
    {
        'slug': 'SharpTongue',
        'name': 'Sharp Tongues',
        'floor': 45.77,
        'supply': 8100,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 230,
        'listed_count': 994,
        'preview_models': ['Lady Night', 'Queen', 'Rainbow', 'Glamour', 'Hypnotic'],
        'preview_backdrop': 'Hunter Green',
        'preview_symbol': 'Ghost',
        'theme': '',
    },
    {
        'slug': 'ArtisanBrick',
        'name': 'Artisan Bricks',
        'floor': 78.95,
        'supply': 6200,
        'models_count': 60,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 953,
        'preview_models': ['Sandstone', 'Concrete', 'Domino', 'Harlequin', 'Delicate Wash'],
        'preview_backdrop': 'Gunmetal',
        'preview_symbol': 'Tetsubin',
        'theme': '',
    },
    {
        'slug': 'MightyArm',
        'name': 'Mighty Arms',
        'floor': 161.9,
        'supply': 3800,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 200,
        'listed_count': 814,
        'preview_models': ['Iron Hook', 'Knockout', 'Squeaker', 'Frankenstein', 'Poor Yorick'],
        'preview_backdrop': 'Steel Grey',
        'preview_symbol': 'Sword Fight',
        'theme': '',
    },
    {
        'slug': 'IonGem',
        'name': 'Ion Gems',
        'floor': 80.0,
        'supply': 4500,
        'models_count': 56,
        'backdrops_count': 60,
        'symbols_count': 263,
        'listed_count': 807,
        'preview_models': ['Solarium', 'Blood Gem', 'Amethyst', 'Star Forge', 'Himalaya'],
        'preview_backdrop': 'Grape',
        'preview_symbol': 'Potion',
        'theme': '',
    },
    {
        'slug': 'NailBracelet',
        'name': 'Nail Bracelets',
        'floor': 109.0,
        'supply': 4700,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 262,
        'listed_count': 802,
        'preview_models': ['Shadow', 'Ultramarine', 'Rose Gold', 'Rose Thorn', 'Argent'],
        'preview_backdrop': 'Emerald',
        'preview_symbol': 'Maple',
        'theme': '',
    },
    {
        'slug': 'MiniOscar',
        'name': 'Mini Oscars',
        'floor': 75.0,
        'supply': 4800,
        'models_count': 100,
        'backdrops_count': 60,
        'symbols_count': 262,
        'listed_count': 775,
        'preview_models': ['Electric', 'Chieftain', 'Undead', 'The Deep', 'Viking'],
        'preview_backdrop': 'Amber',
        'preview_symbol': 'Seahorse',
        'theme': '',
    },
    {
        'slug': 'KhabibsPapakha',
        'name': 'Khabib’s Papakhas',
        'floor': 23.189999999,
        'supply': 29000,
        'models_count': 56,
        'backdrops_count': 80,
        'symbols_count': 161,
        'listed_count': 734,
        'preview_models': ['Wise Elder', 'Long Curls', 'Silver Wings', 'Thunder', 'Chokha'],
        'preview_backdrop': 'Silver Blue',
        'preview_symbol': 'Lotus Flower',
        'theme': 'Fashion',
    },
    {
        'slug': 'AstralShard',
        'name': 'Astral Shards',
        'floor': 155.0,
        'supply': 5600,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 198,
        'listed_count': 656,
        'preview_models': ['Emerald', 'Spinel', 'Sapphire', 'Moonstone', 'Ocean Jasper'],
        'preview_backdrop': 'Persimmon',
        'preview_symbol': 'Inguz Rune',
        'theme': 'Mystical',
    },
    {
        'slug': 'HeroicHelmet',
        'name': 'Heroic Helmets',
        'floor': 212.95,
        'supply': 3400,
        'models_count': 50,
        'backdrops_count': 80,
        'symbols_count': 263,
        'listed_count': 626,
        'preview_models': ['Athena', 'Ancient Gold', 'Aegean Sea', 'Hard Hat', 'Desert Camo'],
        'preview_backdrop': 'Carrot Juice',
        'preview_symbol': 'Black Cat',
        'theme': 'Gaming',
    },
    {
        'slug': 'MagicPotion',
        'name': 'Magic Potions',
        'floor': 70.0,
        'supply': 4800,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 139,
        'listed_count': 499,
        'preview_models': ['Green Goo', 'Saltwater', 'Black Bile', 'Angry Amethyst', 'Dimensional'],
        'preview_backdrop': 'Satin Gold',
        'preview_symbol': 'Spider Web',
        'theme': '',
    },
    {
        'slug': 'PerfumeBottle',
        'name': 'Perfume Bottles',
        'floor': 77.0,
        'supply': 4400,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 289,
        'listed_count': 486,
        'preview_models': ['Millet Fields', 'Azure Plum', 'Crimson Sky', 'Solar Eclipse', 'Orchard Glow'],
        'preview_backdrop': 'Indigo Dye',
        'preview_symbol': 'Bunny Ears',
        'theme': '',
    },
    {
        'slug': 'PreciousPeach',
        'name': 'Precious Peaches',
        'floor': 350.0,
        'supply': 3000,
        'models_count': 80,
        'backdrops_count': 60,
        'symbols_count': 288,
        'listed_count': 395,
        'preview_models': ['Rosegold', 'Ripe Pink', 'Pyrite', 'Bright Amber', 'Mardi Gras'],
        'preview_backdrop': 'Emerald',
        'preview_symbol': 'Dessert',
        'theme': 'Food',
    },
    {
        'slug': 'PlushPepe',
        'name': 'Plush Pepes',
        'floor': 6868.0,
        'supply': 2800,
        'models_count': 50,
        'backdrops_count': 60,
        'symbols_count': 280,
        'listed_count': 384,
        'preview_models': ['Polka Dots', 'Hue Jester', 'Poison Dart', 'Gummy Frog', 'Eggplant'],
        'preview_backdrop': 'Sapphire',
        'preview_symbol': 'Cupid’s Arrow',
        'theme': 'Meme',
    },
    {
        'slug': 'DurovsCap',
        'name': 'Durov’s Caps',
        'floor': 605.0,
        'supply': 4700,
        'models_count': 55,
        'backdrops_count': 60,
        'symbols_count': 198,
        'listed_count': 367,
        'preview_models': ['Krueger', 'Shadow', 'Creamsicle', 'Duskwave', 'Ivory'],
        'preview_backdrop': 'Black',
        'preview_symbol': 'Star',
        'theme': 'Fashion',
    },
    {
        'slug': 'HeartLocket',
        'name': 'Heart Lockets',
        'floor': 1800.0,
        'supply': 1900,
        'models_count': 60,
        'backdrops_count': 80,
        'symbols_count': 236,
        'listed_count': 218,
        'preview_models': ['Disco', 'Azure Gem', 'Toy Joy', 'Nightclub', 'Comic Book'],
        'preview_backdrop': 'Desert Sand',
        'preview_symbol': 'Cocktail',
        'theme': 'Valentine',
    },
    {
        'slug': 'Briefcase',
        'name': 'Briefcases',
        'floor': 1.0,
        'supply': 25000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'CoconutCocktail',
        'name': 'Coconut Cocktails',
        'floor': 1.0,
        'supply': 500000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'DurovFigure',
        'name': 'Durov Figures',
        'floor': 1.0,
        'supply': 4100,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'EasterCake',
        'name': 'Easter Cakes',
        'floor': 1.0,
        'supply': 500000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'FountainPen',
        'name': 'Fountain Pens',
        'floor': 1.0,
        'supply': 50000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'Gravestone',
        'name': 'Gravestones',
        'floor': 1.0,
        'supply': 10000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'HockeyMask',
        'name': 'Hockey Masks',
        'floor': 1.0,
        'supply': 250000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'HoodieBear',
        'name': 'Hoodie Bears',
        'floor': 1.0,
        'supply': 20000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'LadyLiberty',
        'name': 'Lady Liberties',
        'floor': 1.0,
        'supply': 300000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'LoveCats',
        'name': 'Love Cats',
        'floor': 1.0,
        'supply': 80000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'MayDay',
        'name': 'May Days',
        'floor': 1.0,
        'supply': 500000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'PeaceStamp',
        'name': 'Peace Stamps',
        'floor': 1.0,
        'supply': 250000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'RamadanLantern',
        'name': 'Ramadan Lanterns',
        'floor': 1.0,
        'supply': 300000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'RedStar',
        'name': 'Red Stars',
        'floor': 1.0,
        'supply': 500000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'SandCastle',
        'name': 'Sand Castles',
        'floor': 1.0,
        'supply': 150000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'Sunglasses',
        'name': 'Sunglasses',
        'floor': 1.0,
        'supply': 5000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'Surfboard',
        'name': 'Surfboards',
        'floor': 1.0,
        'supply': 40000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'TelegramCone',
        'name': 'Telegram Cones',
        'floor': 1.0,
        'supply': 500000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'TelegramPin',
        'name': 'Telegram Pins',
        'floor': 1.0,
        'supply': 1000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'TelegramRashguard',
        'name': 'Telegram Rashguards',
        'floor': 1.0,
        'supply': 10000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'TelegramSneakers',
        'name': 'Telegram Sneakers',
        'floor': 1.0,
        'supply': 10000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'TrojanHorse',
        'name': 'Trojan Horses',
        'floor': 1.0,
        'supply': 10000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'VampireCoffin',
        'name': 'Vampire Coffins',
        'floor': 1.0,
        'supply': 40000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
    {
        'slug': 'WomensDay',
        'name': "Women's Day",
        'floor': 1.0,
        'supply': 150000,
        'models_count': 0,
        'backdrops_count': 0,
        'symbols_count': 0,
        'listed_count': 0,
        'preview_models': [],
        'preview_backdrop': None,
        'preview_symbol': None,
        'theme': '',
    },
]
